src/main/java/br/eti/cvm/cadastrocrud/bean/LanguageBean.java
package br.eti.cvm.cadastrocrud.bean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.Application;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import lombok.Getter;
import lombok.Setter;

@Named
@SessionScoped
public class LanguageBean implements Serializable {
	private static final long serialVersionUID = 1L;

	@Inject
	private FacesContext facesContext;

	@Getter
	private List<Locale> available;

	@Getter
	@Setter
	private Locale current;

	@PostConstruct
	private void init() {
		Application app = facesContext.getApplication();
		current = app.getViewHandler().calculateLocale(facesContext);
		available = new ArrayList<>();
		available.add(app.getDefaultLocale());
		app.getSupportedLocales().forEachRemaining(available::add);
	}

	public void reload() {
		facesContext.getPartialViewContext().getEvalScripts().add("location.replace(location)");
	}

	public String getLanguageTag() {
		return current.toLanguageTag();
	}

	public void setLanguageTag(String languageTag) {
		current = Locale.forLanguageTag(languageTag);
	}
}

src/main/java/br/eti/cvm/cadastrocrud/bean/LoadDataBean.java
package br.eti.cvm.cadastrocrud.bean;

import java.util.Random;

import javax.annotation.PostConstruct;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import org.omnifaces.cdi.Startup;

import br.eti.cvm.cadastrocrud.model.Person;
import br.eti.cvm.cadastrocrud.model.PersonDetails;

@Startup
public class LoadDataBean {

	@PostConstruct
	private void init() {

		Random random = new Random();

		String[] randomWords = { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto",
				"Setembro", "Outubro", "Novembro", "Dezembro", "Domingo", "Segunda", "Terça", "Quarta", "Quinta",
				"Sexta", "Sabado", "Manha", "Tarde", "Noite", "Sol", "Lua", "Chuva", "Vento", "Fogo", "Terra", "Gelo",
				"Branco", "Preto", "Azul", "Verde", "Vermelho", "Marrom", "Cinza", "Laranja", "Amarelo", "Uva", "Maçã",
				"Pera", "Abacaxi", "Kiwi", "Banana", "Limao", "Ameixa", "Damasco" };

		int length = randomWords.length;
		
		EntityManagerFactory factory = Persistence.createEntityManagerFactory("cadastrocrud-persistence-unit");
		EntityManager em = factory.createEntityManager();

		for (int i = 0; i < 15; i++) {
			String email = randomWords[random.nextInt(length)] + "@" + randomWords[random.nextInt(length)] + "."
					+ randomWords[random.nextInt(length)];

			PersonDetails details = PersonDetails.builder().age(random.nextInt(length))
					.address(randomWords[random.nextInt(length)]).city(randomWords[random.nextInt(length)])
					.zipCode(String.valueOf(70000 + 100 * random.nextInt(length)))
					.telephone(String.valueOf(random.nextInt(length))).info(randomWords[random.nextInt(length)])
					.build();

			Person person = Person.builder().firstName(randomWords[random.nextInt(length)])
					.lastName(randomWords[random.nextInt(length)]).email(email).details(details).build();
			
			em.getTransaction().begin();
			
			em.persist(person);
			
			em.getTransaction().commit();
		}
		
		em.close();
		factory.close();
	}
}

src/main/java/br/eti/cvm/cadastrocrud/bean/ProjectStageBean.java
package br.eti.cvm.cadastrocrud.bean;

import javax.annotation.PostConstruct;
import javax.enterprise.context.ApplicationScoped;
import javax.faces.application.Application;
import javax.faces.application.ProjectStage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;

@ApplicationScoped
public class ProjectStageBean {
	private Boolean isNotProduction = Boolean.FALSE;

	@Inject
	private FacesContext facesContext;

	@PostConstruct
	private void init() {
		Application app = facesContext.getApplication();
		if (app != null) {
			ProjectStage stage = app.getProjectStage();
			if (!ProjectStage.Production.equals(stage)) {
				this.isNotProduction = Boolean.TRUE;
			}
		}
	}

	public Boolean isNotProduction() {
		return this.isNotProduction;
	}
}

src/main/java/br/eti/cvm/cadastrocrud/bean/SessionLogoutBean.java
package br.eti.cvm.cadastrocrud.bean;

import java.io.Serializable;

import javax.enterprise.context.SessionScoped;
import javax.faces.context.ExternalContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;

@Named
@SessionScoped
public class SessionLogoutBean implements Serializable {
	private static final long serialVersionUID = 1L;

	@Inject
	private ExternalContext externalContext;

	public String logout() {
		HttpServletRequest request = (HttpServletRequest) externalContext.getRequest();
		try {
			request.logout();
		} catch (ServletException e) {
			e.printStackTrace();
		}

		return "retrieve?faces-redirect=true";
	}
}

src/main/java/br/eti/cvm/cadastrocrud/bean/ThemeBean.java
package br.eti.cvm.cadastrocrud.bean;

import java.io.Serializable;
import java.util.Arrays;
import java.util.List;

import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

import lombok.Getter;
import lombok.Setter;

@Named
@SessionScoped
public class ThemeBean implements Serializable {
	private static final long serialVersionUID = 1L;
	
	@Getter
	@Setter
	private String theme = "omega";

	public List<String> getThemes() {
		return Arrays.asList("afterdark", "afternoon", "afterwork", "aristo", "black-tie", "blitzer", "bluesky",
				"bootstrap", "casablanca", "cruze", "cupertino", "dark-hive", "delta", "dot-luv", "eggplant",
				"excite-bike", "flick", "glass-x", "home", "hot-sneaks", "humanity", "le-frog", "midnight", "mint-choc",
				"omega", "overcast", "pepper-grinder", "redmond", "rocket", "sam", "smoothness", "south-street",
				"start", "sunny", "swanky-purse", "trontastic", "ui-darkness", "ui-lightness", "vader");
	}
}

src/main/java/br/eti/cvm/cadastrocrud/bean/UserSessionBean.java
package br.eti.cvm.cadastrocrud.bean;

import java.io.Serializable;
import java.util.ResourceBundle;

import javax.enterprise.context.SessionScoped;
import javax.faces.annotation.ManagedProperty;
import javax.faces.context.ExternalContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;

import org.keycloak.KeycloakSecurityContext;

import lombok.extern.jbosslog.JBossLog;

@Named
@SessionScoped
@JBossLog
public class UserSessionBean implements Serializable {
	private static final long serialVersionUID = 1L;

	@Inject
	@ManagedProperty("#{label}")
	private ResourceBundle label;

	@Inject
	private ExternalContext externalContext;

	public String getUserName() {

		try {
			HttpServletRequest request = (HttpServletRequest) externalContext.getRequest();

			KeycloakSecurityContext ksc = (KeycloakSecurityContext) request
					.getAttribute(KeycloakSecurityContext.class.getName());

			return ksc != null ? ksc.getToken().getPreferredUsername() : "";
		} catch (Throwable e) {
//			log.error("Não foi possível obter o usuário logado", e);
		}

		return null;
	}

	public String getFullName() {

		try {
			HttpServletRequest request = (HttpServletRequest) externalContext.getRequest();

			KeycloakSecurityContext ksc = (KeycloakSecurityContext) request
					.getAttribute(KeycloakSecurityContext.class.getName());

			return ksc != null ? ksc.getToken().getName() : "";
		} catch (Throwable e) {
//			log.error("Não foi possível obter o usuário logado", e);
		}

		return null;
	}
}

src/main/java/br/eti/cvm/cadastrocrud/bean/crud/CreateBean.java
package br.eti.cvm.cadastrocrud.bean.crud;

import java.util.ResourceBundle;

import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.faces.annotation.ManagedProperty;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.context.Flash;
import javax.faces.validator.ValidatorException;
import javax.inject.Inject;
import javax.inject.Named;

import br.eti.cvm.cadastrocrud.model.Person;
import br.eti.cvm.cadastrocrud.service.LogService;
import br.eti.cvm.cadastrocrud.service.PersonService;
import lombok.Getter;
import lombok.Setter;

@Named
@RequestScoped
public class CreateBean {

	@Getter
	@Setter
	private Person person;

	@Inject
	private PersonService personService;

	@Inject
	private Flash flash;

	@Inject
	private FacesContext facesContext;

	@Inject
	@ManagedProperty("#{label}")
	private ResourceBundle label;

	@Inject
	private LogService logService;

	@PostConstruct
	private void init() {
		logService.logInfo("método init foi chamado");

		person = new Person();
	}

	public String saveAction() {
		logService.logInfo("método salvar foi chamado");

		personService.create(person);

		flash.setKeepMessages(true);
		facesContext.addMessage(null, new FacesMessage(label.getString("recordcreatedsuccessfully")));

		return "retrieve?faces-redirect=true";
	}

	public void validateEmailDuplicated(FacesContext context, UIComponent component, Object value)
			throws ValidatorException {
		logService.logInfo("método validateEmailRepetido foi chamado");

		Person person = personService.findByEmail((String) value);
		if (person != null) {
			throw new ValidatorException(new FacesMessage(FacesMessage.SEVERITY_ERROR,
					label.getString("emailcannotbeduplicated"), label.getString("emailcannotbeduplicated")));
		}

		return;
	}

}

src/main/java/br/eti/cvm/cadastrocrud/bean/crud/DeleteBean.java
package br.eti.cvm.cadastrocrud.bean.crud;

import java.util.ResourceBundle;

import javax.enterprise.context.RequestScoped;
import javax.faces.annotation.ManagedProperty;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.context.Flash;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.OptimisticLockException;
import javax.transaction.Transactional;

import br.eti.cvm.cadastrocrud.model.Person;
import br.eti.cvm.cadastrocrud.service.LogService;
import br.eti.cvm.cadastrocrud.service.PersonService;
import lombok.Getter;
import lombok.Setter;

@Named
@RequestScoped
public class DeleteBean {

	@Getter
	@Setter
	@Inject
	@ManagedProperty("#{flash.keep.person}")
	private Person person;

	@Inject
	private PersonService personService;

	@Inject
	private Flash flash;

	@Inject
	private FacesContext facesContext;

	@Inject
	@ManagedProperty("#{label}")
	private ResourceBundle label;

	@Inject
	private LogService logService;

	@Transactional
	public String deleteAction() {
		logService.logInfo("método excluirAction foi chamado");

		try {
			Person managed = personService.update(person);
			personService.delete(managed);
		} catch (OptimisticLockException e) {
			facesContext.addMessage(null,
					new FacesMessage(FacesMessage.SEVERITY_WARN, label.getString("optimisticlock"), null));
			return null;
		}

		flash.setKeepMessages(true);
		facesContext.addMessage(null, new FacesMessage(label.getString("recorddeletedsuccessfully")));

		return "retrieve?faces-redirect=true";
	}

}

src/main/java/br/eti/cvm/cadastrocrud/bean/crud/RetrieveBean.java
package br.eti.cvm.cadastrocrud.bean.crud;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.ResourceBundle;

import javax.annotation.PostConstruct;
import javax.faces.annotation.ManagedProperty;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.context.Flash;
import javax.faces.event.ActionEvent;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.model.LazyDataModel;
import org.primefaces.model.SortOrder;

import br.eti.cvm.cadastrocrud.model.Person;
import br.eti.cvm.cadastrocrud.service.LogService;
import br.eti.cvm.cadastrocrud.service.PersonService;
import lombok.Getter;
import lombok.Setter;

@Named
@ViewScoped
public class RetrieveBean implements Serializable {
	private static final long serialVersionUID = 1L;

	@Getter
	@Setter
	private String firstName;

	@Getter
	@Setter
	private String lastName;

	@Getter
	@Setter
	private String email;

	@Getter
	@Setter
	private Person personSelected;

	@Getter
	private LazyDataModel<Person> tablePaginated;

	@Inject
	PersonService personService;

	@Inject
	private Flash flash;

	@Inject
	private FacesContext facesContext;

	@Inject
	@ManagedProperty("#{label}")
	private ResourceBundle label;
	
	@Inject
	LogService logService;

	@PostConstruct
	private void init() {
		logService.logInfo("método init foi chamado");

		firstName = new String();
		lastName = new String();
		email = new String();

		tablePaginated = new LazyDataModel<Person>() {
			private static final long serialVersionUID = 1L;

			private List<Person> datasource = new ArrayList<Person>();

			@Override
			public Person getRowData(String rowKey) {
				logService.logInfo("rowKey = " + rowKey);

				Long id = Long.valueOf(rowKey);

				for (Person person : datasource) {
					if (id.equals(person.getId()))
						return person;
				}

				return null;
			}

			@Override
			public List<Person> load(int first, int pageSize, String sortField, SortOrder sortOrder,
					Map<String, Object> filters) {
				datasource = personService.searchByFullNameEmail(firstName, lastName, email, first, pageSize);

				tablePaginated.setRowCount(personService.count().intValue());

				return datasource;
			}
		};
	}

	public String createAction() {
		logService.logInfo("método createAction foi chamado");

		flash.putNow("person", personSelected);

		return "create?faces-redirect=true";
	}

	public String updateAction() {
		logService.logInfo("método updateAction foi chamado");

		if (personSelected == null) {
			facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN,
					label.getString("norecordselected"), label.getString("norecordselected")));
			return null;
		}

		flash.putNow("person", personSelected);

		return "update?faces-redirect=true";
	}

	public String deleteAction() {
		logService.logInfo("método deleteAction foi chamado");

		if (personSelected == null) {
			facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN,
					label.getString("norecordselected"), label.getString("norecordselected")));
			return null;
		}

		flash.putNow("person", personSelected);

		return "delete?faces-redirect=true";
	}

	public void cleanSearch(ActionEvent actionEvent) {
		firstName = new String();
		lastName = new String();
		email = new String();
	}

}

src/main/java/br/eti/cvm/cadastrocrud/bean/crud/UpdateBean.java
package br.eti.cvm.cadastrocrud.bean.crud;

import java.util.ResourceBundle;

import javax.enterprise.context.RequestScoped;
import javax.faces.annotation.ManagedProperty;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.context.Flash;
import javax.faces.validator.ValidatorException;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.OptimisticLockException;

import br.eti.cvm.cadastrocrud.model.Person;
import br.eti.cvm.cadastrocrud.service.LogService;
import br.eti.cvm.cadastrocrud.service.PersonService;
import lombok.Getter;
import lombok.Setter;

@Named
@RequestScoped
public class UpdateBean {

	@Getter
	@Setter
	@Inject
	@ManagedProperty("#{flash.keep.person}")
	private Person person;

	@Inject
	private PersonService personService;

	@Inject
	private Flash flash;

	@Inject
	private FacesContext facesContext;

	@Inject
	@ManagedProperty("#{label}")
	private ResourceBundle label;

	@Inject
	private LogService logService;

	public String updateAction() {
		logService.logInfo("método atualizarAction foi chamado");

		try {
			personService.update(person);
		} catch (OptimisticLockException e) {
			facesContext.addMessage(null,
					new FacesMessage(FacesMessage.SEVERITY_WARN, label.getString("optimisticlock"), null));
			return null;
		}

		flash.setKeepMessages(true);

		facesContext.addMessage(null, new FacesMessage(label.getString("recordupdatedsuccessfully")));

		return "retrieve?faces-redirect=true";
	}

	public void validateEmailDuplicated(FacesContext context, UIComponent component, Object value)
			throws ValidatorException {
		logService.logInfo("método validateEmailRepetido foi chamado");

		String email = (String) value;
		Person personRetrieved = personService.findByEmail(email);
		if ((personRetrieved != null) && !person.getEmail().equals(personRetrieved.getEmail())) {
			throw new ValidatorException(
					new FacesMessage(FacesMessage.SEVERITY_ERROR, null, label.getString("emailcannotbeduplicated")));
		}

		return;
	}

}

src/main/java/br/eti/cvm/cadastrocrud/config/ConfigBean.java
package br.eti.cvm.cadastrocrud.config;

import javax.enterprise.context.ApplicationScoped;
import javax.faces.annotation.FacesConfig;

@FacesConfig(version = FacesConfig.Version.JSF_2_3)
@ApplicationScoped
public class ConfigBean {

}

src/main/webapp/create.xhtml
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	template="/resources/template/template.xhtml">

	<ui:param name="pageTitle" value="Cadastro CRUD" />

	<ui:define name="header">
		#{label['registry']}
	</ui:define>

	<ui:define name="subheader">
		#{label['create']}
	</ui:define>

	<ui:define name="main">
		<h:form id="formCreate" prependId="false">
			<p:outputPanel id="panel">
				<p:messages showDetail="false" closable="true">
					<p:autoUpdate />
				</p:messages>
				<p:panelGrid columns="2" columnClasses="label,value" styleClass="noBorders">
					<p:outputLabel value="#{label['firstname']}:" for="idField1" />
					<p:inputText id="idField1"
						value="#{createBean.person.firstName}" required="true" />

					<p:outputLabel value="#{label['lastname']}:" for="idField2" />
					<p:inputText id="idField2"
						value="#{createBean.person.lastName}" required="true" />

					<p:outputLabel value="#{label['email']}:" for="idField3" />
					<p:inputText id="idField3" value="#{createBean.person.email}"
						required="true" validator="#{createBean.validateEmailDuplicated}" />

					<p:outputLabel value="#{label['age']}:" for="idField4" />
					<p:inputText id="idField4"
						value="#{createBean.person.details.age}" />

					<p:outputLabel value="#{label['address']}:" for="idField5" />
					<p:inputText id="idField5"
						value="#{createBean.person.details.address}" />

					<p:outputLabel value="#{label['zipcode']}:" for="idField6" />
					<p:inputText id="idField6" value="#{createBean.person.details.zipCode}" />

					<p:outputLabel value="#{label['city']}:" for="idField7" />
					<p:inputText id="idField7"
						value="#{createBean.person.details.city}" />

					<p:outputLabel value="#{label['telephone']}:" for="idField8" />
					<p:inputText id="idField8"
						value="#{createBean.person.details.telephone}" />

					<p:outputLabel value="#{label['info']}:" for="idInfo" />
					<p:inputText id="idInfo" value="#{createBean.person.details.info}" />
				</p:panelGrid>
				<p:panelGrid columns="3" styleClass="noBorders">
					<p:commandButton value="#{label['create']}" action="#{createBean.saveAction}" />
					<p:commandButton value="#{label['clean']}" update="panel" process="@this">
						<p:resetInput target="panel" />
					</p:commandButton>
					<p:commandButton value="#{label['back']}" onclick="window.history.back();" />
				</p:panelGrid>
			</p:outputPanel>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/delete.xhtml
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	template="/resources/template/template.xhtml">

	<ui:param name="pageTitle" value="Cadastro CRUD" />

	<ui:define name="header">
		#{label['registry']}
	</ui:define>

	<ui:define name="subheader">
		#{label['delete']}
	</ui:define>

	<ui:define name="main">
		<h:form id="formDelete" prependId="false">
			<p:outputPanel>
				<p:messages showDetail="false" closable="true">
					<p:autoUpdate />
				</p:messages>
				<p:panelGrid columns="2" columnClasses="label,value" styleClass="noBorders">
					<p:outputLabel value="#{label['firstname']}:" for="idField1" />
					<p:inputText id="idField1"
						value="#{deleteBean.person.firstName}" readonly="true" />

					<p:outputLabel value="#{label['lastname']}:" for="idField2" />
					<p:inputText id="idField2"
						value="#{deleteBean.person.lastName}" readonly="true" />

					<p:outputLabel value="#{label['email']}:" for="idField3" />
					<p:inputText id="idField3" value="#{deleteBean.person.email}"
						readonly="true" />

					<p:outputLabel value="#{label['age']}:" for="idField4" />
					<p:inputText id="idField4"
						value="#{deleteBean.person.details.age}" readonly="true" />

					<p:outputLabel value="#{label['address']}:" for="idField5" />
					<p:inputText id="idField5"
						value="#{deleteBean.person.details.address}" readonly="true" />

					<p:outputLabel value="#{label['zipcode']}:" for="idField6" />
					<p:inputText id="idField6" value="#{deleteBean.person.details.zipCode}"
						readonly="true" />

					<p:outputLabel value="#{label['city']}:" for="idField7" />
					<p:inputText id="idField7"
						value="#{deleteBean.person.details.city}" readonly="true" />

					<p:outputLabel value="#{label['telephone']}:" for="idField8" />
					<p:inputText id="idField8"
						value="#{deleteBean.person.details.telephone}" readonly="true" />

					<p:outputLabel value="#{label['info']}:" for="idField9" />
					<p:inputText id="idField9" value="#{deleteBean.person.details.info}"
						readonly="true" />
				</p:panelGrid>
				<p:panelGrid columns="2" styleClass="noBorders">
					<p:commandButton value="#{label['delete']}"
						action="#{deleteBean.deleteAction}"
						disabled="#{empty deleteBean.person}" />
					<p:commandButton value="#{label['back']}" onclick="window.history.back();" />
				</p:panelGrid>	
			</p:outputPanel>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/error.xhtml
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/resources/template/template.xhtml">

	<ui:param name="pageTitle" value="Server error" />

	<ui:define name="header">
		Oops
	</ui:define>

	<ui:define name="subheader">
		That's going to leave a mark!
	</ui:define>

	<ui:define name="main">
		<h3>Fix the error then try again.</h3>
		<h3>Live long and prosper.</h3>
	</ui:define>

</ui:composition>

src/main/webapp/index.xhtml
<meta http-equiv="refresh" content="0;url=./retrieve.xhtml" /> 

src/main/webapp/language.xhtml
<!DOCTYPE html>
<ui:composition lang="#{languageBean.languageTag}"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	template="/resources/template/template.xhtml">
	<ui:param name="pageTitle" value="Cadastro CRUD" />

	<ui:define name="header">
		#{label['registry']}
	</ui:define>

	<ui:define name="subheader">
		#{label['language']}
	</ui:define>

	<ui:define name="main">
		<h:form id="formLanguage" prependId="false">
			<p:panelGrid columns="2" cellpadding="20" styleClass="noBorders">
				<p:outputLabel value="#{label['language']}:" for="idSelecao" />
				<p:selectOneMenu id="idSelecao" value="#{languageBean.languageTag}">
					<f:selectItems value="#{languageBean.available}" var="l"
						itemValue="#{l.toLanguageTag()}"
						itemLabel="#{l.getDisplayLanguage(l)}" />
					<f:ajax listener="#{languageBean.reload()}" />
				</p:selectOneMenu>
			</p:panelGrid>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/theme.xhtml
<!DOCTYPE html>
<ui:composition lang="#{languageBean.languageTag}"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	template="/resources/template/template.xhtml">
	<ui:param name="pageTitle" value="Cadastro CRUD" />

	<ui:define name="header">
		#{label['registry']}
	</ui:define>

	<ui:define name="subheader">
		#{label['theme']}
	</ui:define>

	<ui:define name="main">
		<h:form id="formTheme" prependId="false">
			<p:panelGrid columns="2" cellpadding="20" styleClass="noBorders">
				<p:outputLabel value="#{label['theme']}:" />
				<p:themeSwitcher value="#{themeBean.theme}" style="width:165px">
					<f:selectItems value="#{themeBean.themes}" />
					<p:ajax />
				</p:themeSwitcher>
			</p:panelGrid>
		</h:form>
	</ui:define>
</ui:composition>