src/main/java/br/eti/cvm/cadastrocrud/bean/UserSessionBean.java
package br.eti.cvm.cadastrocrud.bean;

import java.io.Serializable;
import java.util.ResourceBundle;

import javax.enterprise.context.SessionScoped;
import javax.faces.annotation.ManagedProperty;
import javax.faces.context.ExternalContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;

import org.keycloak.KeycloakSecurityContext;

import lombok.extern.jbosslog.JBossLog;

@Named
@SessionScoped
@JBossLog
public class UserSessionBean implements Serializable {
	private static final long serialVersionUID = 1L;

	@Inject
	@ManagedProperty("#{label}")
	private ResourceBundle label;

	@Inject
	private ExternalContext externalContext;

	public String getUserName() {

		try {
			HttpServletRequest request = (HttpServletRequest) externalContext.getRequest();

			KeycloakSecurityContext ksc = (KeycloakSecurityContext) request
					.getAttribute(KeycloakSecurityContext.class.getName());

			return ksc != null ? ksc.getToken().getPreferredUsername() : "";
		} catch (Throwable e) {
//			log.error("Não foi possível obter o usuário logado", e);
		}

		return null;
	}

	public String getFullName() {

		try {
			HttpServletRequest request = (HttpServletRequest) externalContext.getRequest();

			KeycloakSecurityContext ksc = (KeycloakSecurityContext) request
					.getAttribute(KeycloakSecurityContext.class.getName());

			return ksc != null ? ksc.getToken().getName() : "";
		} catch (Throwable e) {
//			log.error("Não foi possível obter o usuário logado", e);
		}

		return null;
	}
}

src/main/webapp/resources/template/template.xhtml
<!DOCTYPE html>
<html lang="#{languageBean.languageTag}"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<f:view locale="#{languageBean.current}">
	<h:head>
		<title>#{empty pageTitle ? 'Page Title' : pageTitle}</title>
		<link rel="icon" href='#{resource["images/favicon.ico"]}' />
		<h:outputStylesheet library="css" name="template.css" />
		<h:outputStylesheet library="webjars"
			name="font-awesome/5.6.1/css/all.min.css" />
		<h:outputScript library="webjars"
			name="font-awesome/5.6.1/js/all.min.js" />
	</h:head>

	<h:body>
		<h:form prependId="false">
			<p:menubar>
				<p:menuitem value="#{label['retrieve']}" url="${request.contextPath}/retrieve.xhtml" />
				<p:menuitem value="#{label['create']}" url="${request.contextPath}/create.xhtml" />
				<p:menuitem value="#{label['language']}" url="${request.contextPath}/language.xhtml" />
				<p:menuitem value="#{label['theme']}" url="${request.contextPath}/theme.xhtml" />
				<p:menuitem value="#{label['logout']}"
					action="#{sessionLogoutBean.logout}" />
			</p:menubar>
		</h:form>
		<ui:debug
			rendered="#{facesContext.application.projectStage == 'Development'}" />
		<p:panel style="border: 0">
			<p:outputLabel 
				value="#{''.concat(label['user']).concat(': ').concat(userSessionBean.userName)
				.concat(', ').concat(label['fullname']).concat(': ').concat(userSessionBean.fullName)}" rendered="#{!empty userSessionBean.userName and !empty userSessionBean.fullName}"/>
			<div class="ui-g">
				<div class="ui-g-12">
					<h:outputText value="#{label['development']}"
						rendered="#{facesContext.application.projectStage == 'Development'}"
						style="color: red; border: 1px solid red; padding: 2px; margin: 2px; position: absolute; right: 20px" />
				</div>

				<div class="ui-g-12 ui-md-6 ui-lg-3">
					<h1>
						<ui:insert name="header" />
					</h1>
					<h2>
						<ui:insert name="subheader" />
					</h2>
				</div>

				<div class="ui-g-12">
					<ui:insert name="main" />
				</div>
			</div>
		</p:panel>
	</h:body>
</f:view>
</html>